var = 1
import os
import sys
import time
clear = lambda:os.system('clear')
clear()
print ('\033[3;31m ---Welcome to THE GREAT DRAGON SEARCH!--- ')
print ('\n')
time.sleep (3)
print ('In this game, you must read each paragraph and follow')
print ('the directions. Answer each question with one to two ')
print ('word answers. The choices are UPPERCASED. If you misspell') 
print ('anything, the game will restart. You are a great dragon')
print ('hunter. You are out to capture a great Gold Reef dragon.')
print ('You have heard that some have been spotted in the south-')
print ('ern sea.')
print ('\n')
while var== 1:
	ask1=input ('Are you ready to start the game?       ')
	print ('\n')
	if ask1== ('yes'):
		print ('You are at the center of a  crossroads. Three roads lead')
		print ('out of the crossroads. One leads NORTH, one leads SOUTHWEST,')
		print ('and one leads SOUTHEAST.')
		print ('\n')
		time.sleep (3)
		ask2=input ('Which direction will you go?       ')
		print ('\n')
		if ask2== ('north'):
			print ('You travel north. However, you are bitten by a poison')
			print ('spider snake. You die the next day.')
			print ('\n')
			time.sleep (3)
		elif ask2== ('southwest'):
			print ('You are promptly eaten by a dragon. Better luck next time!')
			print ('\n')
			time.sleep (3)
		elif ask2== ('southeast'):
			print ('You start walking southeast. After a long day of hiking, ')
			print ('you get to the little town of Debello. You go and get a ')
			print ('room at the local tavern. After unloading, you walk down-')
			print ('stairs to look at the poster board. You see that there is a ')
			print ('dragon hatchery in town. They just happen to have a Jetflash,')
			print ('the dragon that is good for transportation. But it will take')
			print ('all the money you have to buy it.')
			print ('\n')
			time.sleep (3)
			ask3=input ('Will you BUY the dragon, or CONTINUE without it?       ')
			print ('\n')
			if ask3== ('continue'):
				print ('You decide that you need the money more then the dragon. After')
				print ('sleeping the night, you continue your journey. Two days later,')
				print ('you get to the Cursed Bogs. You wish that you could avoid it or')
				print ('fly over it. Now you wish you bought the dragon!')
				print ('\n')
				time.sleep (3)
				ask4=input ('Will you AVOID the bogs, or PUSH through it?       ')
				print ('\n')
				if ask4== ('push'):
					print ('You are captured by the evil Swamp Hag. You are turned into a newt!')
					print ('\n')
					time.sleep (3)
				elif ask4== ('avoid'):
					print ('You decide to go around the bogs. But it take you much longer then to')
					print ('go through the bogs. You need food.')
					print ('\n')
					time.sleep (3)
					ask5=input ('Will you HUNT for food, or WAIT to resupply at a town?       ')
					print ('\n')
					if ask5== ('hunt'):
						print ('You can not find any food. You die.')
						print ('\n')
						time.sleep (3)
					elif ask5== ('wait'):
						print ('You do not get to a town in time. You starve. Better luck next time!')
						print ('\n')
						time.sleep (3)
			elif ask3== ('buy'):
				ask6=input ('"What will you name him?" asks the owner.       ')
				print ('\n')
				print ('The next day, you go to the hatchery to buy the Jetflash. They')
				print ('take all of your money, and you set off. You name your dragon')
				print (''+ask6+ '. You fly off, and continue your journey. After three')
				print ('hours, you reach the Cursed Bogs. If you fly over, you can save')
				print ('time.')
				print ('\n')
				time.sleep (3)
				ask7=input ('Will you fly OVER the bogs, or fly AROUND the bogs?      ')
				print ('\n')
				if ask7== ('over'):
					print ('You want to save time, so you fly over the bogs. However, you are att-')
					print ('acked half way over by a Swamp Hag! She uses magic to knock you out of')
					print ('the sky. When you get up, you see '+ask6+' and the hag fighting. You ')
					print ('want to help.')
					print ('\n')
					time.sleep (3)
					ask8=input ('Will you SHOOT her with fire, or ELECTRIFY her with lightening?       ')
					print ('\n')
					if ask8== ('electrify'):
						print ('You use lightening to kill the hag. But you also kill '+ask6+'. In your grief,')
						print ('you decide to take up turkey farming!')
						print ('\n')
						time.sleep (3)
					elif ask8== ('shoot'):
						print ('You torch the hag, and she dies. Since '+ask6+' is a dragon, he is fine. you re-')
						print ('mount, and fly out of the Cursed Bogs. Soon you get to the town of Flask.')
						print ('\n')
						time.sleep (3)
						ask9=input ('Will you STOP for the night, or CAMP in the nearby forest?       ')
						print ('\n')
						if ask9== ('stop'):
							print ('You stop at the tavern and get a room. Robbers kill you in your sleep to get '+ask6+'.')
							print ('Sucker!')
							print ('\n')
							time.sleep (3)
						elif ask9== ('camp'):
							print ('The sister of the hag you killed kills you in the middle of the night. Try again.')
							print ('\n')
							time.sleep (3)
				elif ask7== ('around'):
					print ('You decide not take the chance with the swamp monsters.(they scare you) ')
					print ('It takes twice as long to fly around the bogs. But you still reach the town')
					print ('of Flask.')
					print ('\n')
					time.sleep (3)
					ask10=input ('Will you CAMP out of town, or sleep at the local TAVERN?       ')
					print ('\n')
					if ask10== ('camp'):
						print ('You are killed in your sleep by another swamp hag. Better luck next time!')
						print ('\n')
						time.sleep (3)
					elif ask10== ('tavern'):
						print ('You make your way to the tavern. '+ask6+' is put in the dragon stable, and')
						print ('you go to sleep. In the middle of the night, you hear '+ask6+' roaring. You')
						print ('rush outside and see that he has been stolen.')
						print ('\n')
						time.sleep (3)
						ask11=input ('Will you RUSH OFF to find '+ask6+', or SLEEP in and abandon him?       ')
						print ('\n')
						if ask11== ('sleep'):
							print ('You abandon '+ask6+'. In the morning, you pack up and keep going.')
							print ('You continue for five more hours. Then you reach the Disappearing ')
							print ('Forest. It has that funny name because every sunset, it disappears.')
							print ('You want to go around, but you do not have a dragon anymore. You ')
							print ('start walking into the forest. You have to make it out before sunset.')
							print ('If you do not, you will disappear with the forest. You walk until ')
							print ('midday. You can not stop eat. One of the black trees suddenly jumps')
							print ('out of the ground and attacks you.')
							print ('\n')
							time.sleep (3)
							ask12=input ('Will you FIGHT BACK, or RUN away?       ')
							print ('\n')
							if ask12== ('fight back'):
								print ('You draw your flaming sword and counter the attack! You die.')
								print ('\n')
								time.sleep (3)
							elif ask12== ('run'):
								print ('You are terrified! You draw your sword and bravely run away.')
								print ('More and more trees follow. Soon it seems as if the whole forest')
								print ('is after you. You try blasting fire balls at them as you run.')
								print ('You torch a few trees, but more chase you. They suddenly stop,')
								print ('and root themselves down where they are. Why did they stop? You')
								print ('can see why. Right in front of you, there is a group of cave trolls!')
								print ('\n')
								time.sleep (3)
								ask13=input ('Will you FIGHT THEM, or SURRENDER?       ')
								print ('\n')
								if ask13== ('fight them'):
									print ('The cave trolls overpower and kill you. Better luck next time!')
									print ('\n')
									time.sleep (3)
								elif ask13== ('surrender'):
									print ('There is no way you could win. They take you captive. They plan to cook')
									print ('you over a fire and eat you. Just when all hope seems lost, a man leaps')
									print ('from the bushes, and uses magic to freeze the trolls in ice! The two of')
									print ('run out of the Disappearing Forest just as the sun sets. Behind you, the')
									print ('forest disappears. The man says he is also a dragon hunter.')
									print ('\n')
									time.sleep (3)
									ask14=input ('Will you GO with the man to the south, or CONTINUE by yourself?       ')
									print ('\n')
									if ask14== ('continue'):
										print ('You leave the man and got it alone. It is a long trip south. After many days,')
										print ('you reach the port of Torrant. You need a boat.')
										print ('\n')
										time.sleep (3)
										ask19=input ('Will you USE MAGIC to make a sailor give you his boat, or BUY one?       ')
										print ('\n')
										if ask19== ('use magic'):
											print ('The sailor can use magic better then you. He makes you work for him for twenty')
											print ('years.')
											print ('\n')
											time.sleep (3)
										elif ask19== ('buy'):
											print ('You have to work for a month to afford a boat. You sail south to the Compass')
											print ('Islands.')
											print ('\n')
											time.sleep (3)
											ask20=input ('Will you GET A ROOM at the tavern, or START hunting for the dragon?       ')
											print ('\n')
											if ask20== ('start'):
												print ('You soon find a Gold Reef Dragon. But sadly, it kills you.')
												print ('\n')
												time.sleep (3)
											elif ask20== ('get a room'):
												print ('You Drop off your things at the tavern. After that, you go hunting')
												print ('After two days, you capture the dragon!!!. But a man kills you and sells')
												print ('the dragon himself. Better luck next time!')
												print ('\n')
												time.sleep (3)
									elif ask14== ('go'):
										print ('The man is named Rush. He takes you to his camp. He has '+ask6+'!')
										print ('\n')
										time.sleep (3)
										ask15=input ('Will you ATTACK Rush and take back '+ask6+', or ASK about him?       ')
										print ('\n')
										if ask15== ('attack'):
											print ('Rush kills you.')
											print ('\n')
											time.sleep (3)
										elif ask15== ('ask'):
											print ('You demand to know why he has '+ask6+'. Rush claims that he took him from')
											print ('a band of ruffians. You believe him. The two of you continue south. '+ask6+'')
											print ('cane fly very fast. After two days, you reach the port of Torrant. You must')
											print ('get a large boat to take you to the Compass islands.')
											print ('\n')
											time.sleep (3)
											ask16=input ('Will you BUY one, or USE MAGIC to convince a sailor to give you his?       ')
											print ('\n')
											if ask16== ('use magic'):
												print ('The sailor can also use magic. He makes you and Rush work for him for twenty years.')
												print ('\n')
												time.sleep (3)
											elif ask16== ('buy'):
												print ('You have to work for a few days to get the money. (you spent all yours on '+ask6+') After')
												print ('that, you set off in the right boat. After several days, you reach the islands.')
												print ('\n')
												time.sleep (3)
												ask17=input ('Will you HUNT the dragon now, or GET A ROOM at the Compass Islands Tavern?       ')
												print ('\n')
												if ask17== ('hunt'):
													print ('You and Rush go and start hunting as soon as you get off the boat. You see the dragon!!!')
													print ('You are killed in the process of capturing it. Rush sells him and gets rich.')
													print ('\n')
													time.sleep (3)
												elif ask17== ('get a room'):
													print ('You and Rush get a room, then start hunting.')
													print ('\n')
													time.sleep (3)
													ask21=input ('Will you SET TRAPS, or CHASE the dragon?       ')
													print ('\n')
													if ask21== ('chase'):
														print ('The dragons ambush you and torch you to death.')
														print ('\n')
														time.sleep (3)
													elif ask21== ('set traps'):
														print ('You and Rush cunningly set several traps all around the island. The next day, you ')
														print ('check them all. In one trap, You have a Gold Reef Dragon!!!')
														print ('\n')
														time.sleep (3)
														ask22=input ('Will you SNEAK the dragon off the island, or SHIP it in the boat?       ')
														print ('\n')
														if ask22== ('ship'):
															print ('Right after you and Rush load up the dragon, a band of man launch a small boat and chase')
															print ('you. They catch you and kill you without mercy.')
															print ('\n')
															time.sleep (3)
														elif ask22== ('sneak'):
															print ('You and Rush decide to smuggle the dragon off the islands to avoid attention. You')
															print ('sneak the priceless dragon all the way to the northern markets. ')
															print ('\n')
															time.sleep (3)
															ask18=input ('A rich merchant asks, "How much will you sell him for?"       ')
															print ('\n')
															print ('He buys the dragon for $'+ask18+'. You and Rush are RICH!!!!!!')
															print ('\n')
															print ('Spend the money wisely!')
															print ('\n')
															time.sleep (10)
															sys.exit ()
						elif ask11== ('rush off'):
							print ('The robbers kill you when you catch them. Tough luck.')
							print ('\n')
							time.sleep (3)
	else:
		print ('Loser.')
		time.sleep (10)
		sys.exit ()
